# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Server

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - "dev"
    paths:
      - "Server/*"
  pull_request:
    branches:
      - "master"
    paths:
      - "Server/*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"

      - run: pnpm -F "shorten-url-api" --config.dedupe-peer-dependents=false install

      - run: cd Server/ && pnpm run --if-present build
