# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build Website

on:
  push:
    branches-ignore:
      - "dev"
    paths:
      - "Website/*"
  pull_request:
    branches:
      - "master"
    paths:
      - "Website/*"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        fail-fast: [false]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "Website/"
      - run: cd API/ && npm ci
      - run: cd Website/ && npm ci
      - run: cd Website/ && npm run build --if-present
